[2025-09-02T02:41:27.646+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.archive manual__2025-09-02T02:39:14.118727+00:00 [queued]>
[2025-09-02T02:41:27.677+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.archive manual__2025-09-02T02:39:14.118727+00:00 [queued]>
[2025-09-02T02:41:27.678+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-02T02:41:27.738+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): archive> on 2025-09-02 02:39:14.118727+00:00
[2025-09-02T02:41:27.778+0000] {standard_task_runner.py:60} INFO - Started process 3469 to run task
[2025-09-02T02:41:27.793+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'archive', 'manual__2025-09-02T02:39:14.118727+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpchmh1fwl']
[2025-09-02T02:41:27.830+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask archive
[2025-09-02T02:41:27.946+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-02T02:41:28.155+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.archive manual__2025-09-02T02:39:14.118727+00:00 [running]> on host f8a9cd7e9422
[2025-09-02T02:41:28.436+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='archive' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T02:39:14.118727+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-02T02:39:14.118727+00:00'
[2025-09-02T02:41:30.220+0000] {etl_pipeline.py:208} INFO - Archived 2025/09/02/affe8453-7cb4-4dde-99d4-8da6c44d8f55_applicants.csv from landing -> archive
[2025-09-02T02:41:30.245+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-02T02:41:30.801+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=archive, execution_date=20250902T023914, start_date=20250902T024127, end_date=20250902T024130
[2025-09-02T02:41:31.154+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-02T02:41:31.495+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
