[2025-09-01T05:51:39.353+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.transform manual__2025-09-01T05:51:33.590672+00:00 [queued]>
[2025-09-01T05:51:39.367+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.transform manual__2025-09-01T05:51:33.590672+00:00 [queued]>
[2025-09-01T05:51:39.368+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-01T05:51:39.389+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform> on 2025-09-01 05:51:33.590672+00:00
[2025-09-01T05:51:39.400+0000] {standard_task_runner.py:60} INFO - Started process 560 to run task
[2025-09-01T05:51:39.407+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'transform', 'manual__2025-09-01T05:51:33.590672+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpzs3zcfjt']
[2025-09-01T05:51:39.410+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask transform
[2025-09-01T05:51:39.453+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01T05:51:39.522+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.transform manual__2025-09-01T05:51:33.590672+00:00 [running]> on host 857434650c3d
[2025-09-01T05:51:39.672+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T05:51:33.590672+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-01T05:51:33.590672+00:00'
[2025-09-01T05:51:39.675+0000] {logging_mixin.py:188} INFO - Running task: TRANSFORM
[2025-09-01T05:51:39.675+0000] {logging_mixin.py:188} INFO - Simulating the transformation of extracted data...
[2025-09-01T05:51:39.675+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-01T05:51:39.693+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=transform, execution_date=20250901T055133, start_date=20250901T055139, end_date=20250901T055139
[2025-09-01T05:51:39.752+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-01T05:51:39.799+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
