[2025-09-01T08:39:29.758+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.archive manual__2025-09-01T08:38:48.382430+00:00 [queued]>
[2025-09-01T08:39:29.776+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.archive manual__2025-09-01T08:38:48.382430+00:00 [queued]>
[2025-09-01T08:39:29.777+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-01T08:39:29.804+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): archive> on 2025-09-01 08:38:48.382430+00:00
[2025-09-01T08:39:29.839+0000] {standard_task_runner.py:60} INFO - Started process 240 to run task
[2025-09-01T08:39:29.847+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'archive', 'manual__2025-09-01T08:38:48.382430+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmprd4obet1']
[2025-09-01T08:39:29.850+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask archive
[2025-09-01T08:39:29.871+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01T08:39:29.937+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.archive manual__2025-09-01T08:38:48.382430+00:00 [running]> on host f8a9cd7e9422
[2025-09-01T08:39:30.070+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='archive' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T08:38:48.382430+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-01T08:38:48.382430+00:00'
[2025-09-01T08:39:30.279+0000] {etl_pipeline.py:180} INFO - Archive bucket 'archive' not found. Creating it.
[2025-09-01T08:39:30.338+0000] {etl_pipeline.py:187} INFO - Archived 2025/09/01/51a565fe-9727-4c21-a6d7-d41ded60e1c6_applicants.csv from landing -> archive
[2025-09-01T08:39:30.340+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-01T08:39:30.357+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=archive, execution_date=20250901T083848, start_date=20250901T083929, end_date=20250901T083930
[2025-09-01T08:39:30.404+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-01T08:39:30.431+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
