[2025-08-28T09:18:01.127+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.transform manual__2025-08-28T09:17:52.263515+00:00 [queued]>
[2025-08-28T09:18:01.139+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.transform manual__2025-08-28T09:17:52.263515+00:00 [queued]>
[2025-08-28T09:18:01.140+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-28T09:18:01.159+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform> on 2025-08-28 09:17:52.263515+00:00
[2025-08-28T09:18:01.187+0000] {standard_task_runner.py:60} INFO - Started process 245 to run task
[2025-08-28T09:18:01.208+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'transform', 'manual__2025-08-28T09:17:52.263515+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpehwom3o3']
[2025-08-28T09:18:01.215+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask transform
[2025-08-28T09:18:01.247+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T09:18:01.341+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.transform manual__2025-08-28T09:17:52.263515+00:00 [running]> on host 45d0ac61cfd5
[2025-08-28T09:18:01.614+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T09:17:52.263515+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-28T09:17:52.263515+00:00'
[2025-08-28T09:18:01.628+0000] {logging_mixin.py:188} INFO - Transforming (fake)...
[2025-08-28T09:18:03.631+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-28T09:18:03.704+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=transform, execution_date=20250828T091752, start_date=20250828T091801, end_date=20250828T091803
[2025-08-28T09:18:03.779+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-28T09:18:03.890+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
